POST http://localhost:3000/register/
Content-Type:application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
POST http://localhost:3000/login/
Content-Type:application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc

###
GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc

###
GET http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc


###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc
Content-Type:application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc

###
DELETE http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc

###
PUT http://localhost:3000/districts/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc
Content-Type:application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/1/stats/
Authorization: Beareer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwNTYyNzM0fQ.uMpzR7LWKZNBF5TLNR1n3yiECLChvEZSSmc9l71hfwc
